/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "checksum_generate.v:1" *)
module bitchecksum(data, clk, checksum);
  (* src = "checksum_generate.v:10" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "checksum_generate.v:10" *)
  wire _13_;
  (* src = "checksum_generate.v:3" *)
  wire _14_;
  (* src = "checksum_generate.v:3" *)
  wire _15_;
  (* src = "checksum_generate.v:3" *)
  wire _16_;
  (* src = "checksum_generate.v:3" *)
  wire _17_;
  (* src = "checksum_generate.v:3" *)
  wire _18_;
  (* src = "checksum_generate.v:3" *)
  wire _19_;
  (* src = "checksum_generate.v:3" *)
  wire _20_;
  (* src = "checksum_generate.v:3" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "checksum_generate.v:4" *)
  output [7:0] checksum;
  (* src = "checksum_generate.v:2" *)
  input clk;
  (* src = "checksum_generate.v:3" *)
  input [31:0] data;
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(_15_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _30_ (
    .A(_20_),
    .B(_14_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(_21_),
    .B(_17_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(_23_),
    .B(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21oi_1 _33_ (
    .A1(_22_),
    .A2(_25_),
    .B1(_16_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a31oi_1 _34_ (
    .A1(_22_),
    .A2(_16_),
    .A3(_25_),
    .B1(_18_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nand2b_1 _35_ (
    .A_N(_26_),
    .B(_27_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(_19_),
    .B(_28_),
    .Y(_13_)
  );
  (* src = "checksum_generate.v:10" *)
  sky130_fd_sc_hd__dfxtp_1 _37_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(checksum[0])
  );
  assign _00_[7:1] = 7'h7f;
  assign checksum[7:1] = 7'h7f;
  assign _20_ = data[8];
  assign _14_ = data[0];
  assign _15_ = data[16];
  assign _16_ = data[17];
  assign _18_ = data[23];
  assign _19_ = data[24];
  assign _00_[0] = _13_;
  assign _21_ = data[9];
  assign _17_ = data[1];
endmodule
